### ISSUE TITLE
Broken links in "Contributing to Pegasys Documentation"

### ISSUE THREAD

**Issue by SatpalSandhu61** [PegaSysEng/doc.common#12]
There are a number of broken links in the contribution guidelines:
1. Under the section "[Contribution workflow](https://github.com/PegaSysEng/doc.common/wiki/Contributing-to-Pegasys-Documentation#contribution-workflow)", section 6 contains a link to "MkDocs And Markdown Guide".
The link is `https://github.com/PegaSysEng/doc.common/wiki/MKDOCS-MARKDOWN-GUIDE.md#preview-the-documentation` which does not exist.
Note that the link in the sidebar is correct ("[MkDocs And Custom Markdown Guide](https://github.com/PegaSysEng/doc.common/wiki/MkDocs-And-Custom-Markdown-Guide)")

2. Under the section "[Style guides](https://github.com/PegaSysEng/doc.common/wiki/Contributing-to-Pegasys-Documentation#style-guides)", there is a broken link to "documentation guidelines and examples".
The link is `https://github.com/PegaSysEng/doc.common/wiki/DOC-STYLE-GUIDE.md` which does not exist.
Note that the link in the sidebar is correct ("[Pegasys Documentation Style Guide](https://github.com/PegaSysEng/doc.common/wiki/Pegasys-Documentation-Style-Guide)")

**Comment by MadelineMurray** [comment]
Thanks for raising @SatpalSandhu61

**Comment by NicolasMassart** [comment]
Links are fixed and I also took some time to make a deeper update of the pages.

- updated links
- updated chat to Discord
- updated email links
- updated other broken links (they were broken because we copied the content from a file to the wiki a bit quickly and never updated them, sorry)

Now the page is https://github.com/PegaSysEng/doc.common/wiki/Contributing-to-Documentation (removed Pegasys from the title as we are slowly deprecating the brand)
